version: '3.8'

services:
  rest-api:
    build:
      context: ./rest-api/.devcontainer
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
    networks:
      - default

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=surajboniwal
      - POSTGRES_PASSWORD=1682972780020592640
      - POSTGRES_DB=connect
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

networks:
  default:
    driver: "bridge"
